### ISSUE TITLE
Add `.vscode/tasks.json` for preject.

### ISSUE THREAD

**Issue by freedomhero** [sCrypt-Inc/scrypt-cli#10]
For showing problems in vscode when file saved. The task will run automatically when the project folder opened. Also users can press `shift+cmd+b` to run the task.

The content can be found here: https://github.com/sCrypt-Inc/scryptTS-examples/blob/master/.vscode/tasks.json

**Comment by msinkec** [comment]
Now included in scrypt-cli@0.1.3 

c2e12cb6c8b0f9f8c3f8d9183cb19e0b9171c039
