### ISSUE TITLE
document all CLI options

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scrypt-cli#106]
like `--asm`
https://github.com/sCrypt-Inc/boilerplate/blob/c53ef02fc9fcd131c733ae7bd836e83e77211389/package.json#L8.

Easier for users to know w/o running CLI `--help`.

### --watch
Document what watch option does, like https://create-react-app.dev/docs/running-tests/#command-line-interface

**Comment by msinkec** [comment]
@yusufidimaina9989 
1. Document --watch and --asm options in README.md
2. Find if there's anything else missing in README.md that should be added. Add it if so.
