### ISSUE TITLE
add a watch script

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scrypt-cli#107]
"watch": "npx scrypt-cli compile --watch"

So users can watch sCrypt level errors, which are not TypeScript errors.

Name it `watch`, or `watch:compile`.

Remember to update boilerplate, once added.
https://github.com/sCrypt-Inc/boilerplate/blob/c53ef02fc9fcd131c733ae7bd836e83e77211389/package.json#L8

### Examples
https://gist.github.com/int128/e0cdec598c5b3db728ff35758abdbafd

https://github.com/tookey-io/sats
<img width="970" alt="image" src="https://github.com/sCrypt-Inc/scrypt-cli/assets/1017252/362ee197-abb6-4f91-9db2-0e19ae7529c4">

**Comment by yusufidimaina9989** [comment]
https://github.com/sCrypt-Inc/scrypt-cli/pull/109
