### ISSUE TITLE
linter + prettier

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scrypt-cli#11]
Eslint plugin/prettier per user feedback
https://github.com/sCrypt-Inc/scrypt-ts/issues/95#issue-1526223907

**Comment by msinkec** [comment]
Some things to sort out for prettier:

- Semicolon at the end of a line? yes/no
- Single or double quotes?
- Trailing commas? yes/no
- Max line width? 80 chars?
- Indentation width? 2 or 4 spaces?
- Bracket spacing? {thing} or { thing } ?

Listed here are some other options we could enforce: https://prettier.io/docs/en/options.html

**Comment by xhliu** [comment]
just use whatever is popular, no big deal
