### ISSUE TITLE
support other frameworks?

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scrypt-cli#19]
boilerplate/framework like NextJS & Angular, besides React.

- [ ] Add a guide: How to Support a New Framework, like https://docs.scrypt.io/advanced/how-to-add-a-signer.
- [x] #46 
- [x] Angular
- [x] Vue
- [x] Svelt

Remember to update this list after adding each support https://docs.scrypt.io/how-to-integrate-a-frontend.

### Samples
https://docs.moralis.io/web3-data-api/evm/getting-started/
https://meshjs.dev/starter-templates

**Comment by ielvisd** [comment]
Yes please, I'm a much faster Vue dev than I am a React dev 🙁  

I'm currently trying to figure out how to modify the CLI so that I can compile a contract using this Vue/Vite implementation/framework: https://github.com/antfu/vitesse

**Comment by owenkellogg** [comment]
Definitely pow.co can benefit greatly by a NextJS integration since that is the  framework used.

There are so many contracts I want to deploy and am doing so in a more manual, hackey way than I would prefer if there was a direct integration.

**Comment by xhliu** [comment]
https://docs.minaprotocol.com/zkapps/how-to-write-a-zkapp#option-b-start-your-own-project
https://docs.minaprotocol.com/zkapps/how-to-write-a-zkapp-ui#using-one-of-the-provided-ui-framework-scaffolds
<img width="996" alt="image" src="https://github.com/sCrypt-Inc/scrypt-cli/assets/1017252/3e2e92c1-58b5-43a3-a117-ae380c522f2d">

**Comment by owenkellogg** [comment]
Sweet thank you!!!

**Comment by xhliu** [comment]
Add into homepage, like https://moralis.io/

![Image](https://github.com/sCrypt-Inc/scrypt-cli/assets/1017252/ea640e8e-184c-44ac-b28e-f2aeca92bbe4)

**Comment by gitzhou** [comment]
<img width="1920" alt="image" src="https://github.com/sCrypt-Inc/scrypt-cli/assets/1585505/dc49b4ea-b891-4f0e-b41f-9ca6385f5e95">
