### ISSUE TITLE
scrypt-cli project broken

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scrypt-cli#30]
Add a regression test after fix.
![image](https://user-images.githubusercontent.com/1017252/222798616-8f3e8ede-2883-471a-ab83-4625fb33775d.png)

**Comment by zhfnjust** [comment]
@xhliu  can not reproduce:

<img width="581" alt="image" src="https://user-images.githubusercontent.com/995909/222873219-bedffdca-4bbc-4697-a5df-1680bcbfec29.png">


show your scrypt-cli version by:

```sh
npx scrypt-cli -v
```

if not latest version, try this to upgrade:

https://github.com/sCrypt-Inc/scrypt-cli#using-latest-version

**Comment by xhliu** [comment]
Used globally installed CLI: 0.1.5.
