### ISSUE TITLE
remove unnecessary files

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scrypt-cli#4]
![image](https://user-images.githubusercontent.com/1017252/209577760-ebf4d5c8-71c4-4f1c-a663-8372c07ae612.png)

**Comment by msinkec** [comment]
Those aren't included in the template.

**Comment by xhliu** [comment]
@msinkec  `keys/` is still included 
![image](https://user-images.githubusercontent.com/1017252/212160383-f1493239-ed9f-4388-8ee1-83d52c2170cd.png)
