### ISSUE TITLE
remove privateKey dependency from unit test

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scrypt-cli#8]
in `txHelper.js`
`import { privateKey } from './privateKey'`

Should only be needed in testnet tests.

Update scryptTS & scryptTS-examples as well.

**Comment by msinkec** [comment]
Is this hierarchy suitable? I moved the files under testnet/util/ and removed local tests dependency on it.
https://github.com/sCrypt-Inc/scrypt-cli/tree/2ccaab4cd7920e4356b56703b0486f603a9a6a4b/templates/demo-contract/tests

**Comment by msinkec** [comment]
I think this is good to go then. Will also update structure in other repos.
