### ISSUE TITLE
Exit status 1 when run compile

### ISSUE THREAD

**Issue by cyio** [sCrypt-Inc/scrypt-cli#94]
<img width="1016" alt="image" src="https://github.com/sCrypt-Inc/scrypt-cli/assets/3146103/82ec27a6-ded8-4d87-a40a-cf15f0d7b447">

Step:
1. `npx scrypt-cli project scrypt-demo`
2. `npm i`
3. `npm run build`
4. `npm run test`

error happens

**Comment by zhfnjust** [comment]
did you change `.\src\contracts\scryptDemo.ts`

can you show more error message?

**Comment by cyio** [comment]
[2023-12-13T11_25_23_712Z-debug.log](https://github.com/sCrypt-Inc/scrypt-cli/files/13660106/2023-12-13T11_25_23_712Z-debug.log)

I have not change any file

**Comment by zhfnjust** [comment]
can you try :  npx scrypt-cli@latest system

**Comment by cyio** [comment]
<img width="415" alt="image" src="https://github.com/sCrypt-Inc/scrypt-cli/assets/3146103/5dc7e82b-9e45-4b1d-96d6-fbaeae59ad1a">

**Comment by zhfnjust** [comment]
看起来和 scrypt-cli 本身没有关系， 而是 npx  在 安装 scrypt-cli 的时候失败了。

尝试安装其它包看是否成功， 比如执行 

```
npx create-react-app@latest dapp-react --template typescript
```

**Comment by xhliu** [comment]
@cyio still an issue?
