### ISSUE TITLE
always reinstall when open vscode

### ISSUE THREAD

**Issue by zhfnjust** [sCrypt-Inc/scrypt-cli#95]

**Comment by freedomhero** [comment]
It seems to be caused by that the previously installed npx version at `/usr/local/bin/npx`, which is for node v14.20.0,  is not the same version (for node v16.20.0) at `~/.nvm/versions/node/v16.20.0/bin/npx` while starting the vscode.

The solution is to delete the old ones:

```
rm -rf /usr/local/bin/npm
rm -rf /usr/local/bin/node
rm -rf /usr/local/bin/npx
```
